[package]
name = "macros"
description = "Macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true


[dependencies]
syn = { version = "2.0.100", features = ["full"] }
quote = { version = "1.0.24" }

[package.metadata.docs.rs]
all-features = true
